# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/work/project_AXI_DMA/project_AXI_DMA.srcs/sources_1/bd/system/ip/system_system_ila_0_1/system_system_ila_0_1.xci
# IP: The module: 'system_system_ila_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: e:/work/project_AXI_DMA/project_AXI_DMA.srcs/sources_1/bd/system/ip/system_system_ila_0_1/bd_0/bd_1579.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_1579 || ORIG_REF_NAME==bd_1579} -quiet] -quiet

# IP: e:/work/project_AXI_DMA/project_AXI_DMA.srcs/sources_1/bd/system/ip/system_system_ila_0_1/bd_0/ip/ip_0/bd_1579_ila_lib_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_1579_ila_lib_0 || ORIG_REF_NAME==bd_1579_ila_lib_0} -quiet] -quiet

# IP: e:/work/project_AXI_DMA/project_AXI_DMA.srcs/sources_1/bd/system/ip/system_system_ila_0_1/bd_0/ip/ip_1/bd_1579_g_inst_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_1579_g_inst_0 || ORIG_REF_NAME==bd_1579_g_inst_0} -quiet] -quiet

# IP: e:/work/project_AXI_DMA/project_AXI_DMA.srcs/sources_1/bd/system/ip/system_system_ila_0_1/bd_0/ip/ip_2/bd_1579_slot_0_aw_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_1579_slot_0_aw_0 || ORIG_REF_NAME==bd_1579_slot_0_aw_0} -quiet] -quiet

# IP: e:/work/project_AXI_DMA/project_AXI_DMA.srcs/sources_1/bd/system/ip/system_system_ila_0_1/bd_0/ip/ip_3/bd_1579_slot_0_w_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_1579_slot_0_w_0 || ORIG_REF_NAME==bd_1579_slot_0_w_0} -quiet] -quiet

# IP: e:/work/project_AXI_DMA/project_AXI_DMA.srcs/sources_1/bd/system/ip/system_system_ila_0_1/bd_0/ip/ip_4/bd_1579_slot_0_b_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_1579_slot_0_b_0 || ORIG_REF_NAME==bd_1579_slot_0_b_0} -quiet] -quiet

# IP: e:/work/project_AXI_DMA/project_AXI_DMA.srcs/sources_1/bd/system/ip/system_system_ila_0_1/bd_0/ip/ip_5/bd_1579_slot_0_ar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_1579_slot_0_ar_0 || ORIG_REF_NAME==bd_1579_slot_0_ar_0} -quiet] -quiet

# IP: e:/work/project_AXI_DMA/project_AXI_DMA.srcs/sources_1/bd/system/ip/system_system_ila_0_1/bd_0/ip/ip_6/bd_1579_slot_0_r_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_1579_slot_0_r_0 || ORIG_REF_NAME==bd_1579_slot_0_r_0} -quiet] -quiet

# XDC: e:/work/project_AXI_DMA/project_AXI_DMA.srcs/sources_1/bd/system/ip/system_system_ila_0_1/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_1579_ila_lib_0 || ORIG_REF_NAME==bd_1579_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: e:/work/project_AXI_DMA/project_AXI_DMA.srcs/sources_1/bd/system/ip/system_system_ila_0_1/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_1579_ila_lib_0 || ORIG_REF_NAME==bd_1579_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: e:/work/project_AXI_DMA/project_AXI_DMA.srcs/sources_1/bd/system/ip/system_system_ila_0_1/bd_0/ip/ip_0/bd_1579_ila_lib_0_ooc.xdc

# XDC: e:/work/project_AXI_DMA/project_AXI_DMA.srcs/sources_1/bd/system/ip/system_system_ila_0_1/bd_0/bd_1579_ooc.xdc

# IP: e:/work/project_AXI_DMA/project_AXI_DMA.srcs/sources_1/bd/system/ip/system_system_ila_0_1/system_system_ila_0_1.xci
# IP: The module: 'system_system_ila_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: e:/work/project_AXI_DMA/project_AXI_DMA.srcs/sources_1/bd/system/ip/system_system_ila_0_1/bd_0/bd_1579.bd
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_1579 || ORIG_REF_NAME==bd_1579} -quiet] -quiet

# IP: e:/work/project_AXI_DMA/project_AXI_DMA.srcs/sources_1/bd/system/ip/system_system_ila_0_1/bd_0/ip/ip_0/bd_1579_ila_lib_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_1579_ila_lib_0 || ORIG_REF_NAME==bd_1579_ila_lib_0} -quiet] -quiet

# IP: e:/work/project_AXI_DMA/project_AXI_DMA.srcs/sources_1/bd/system/ip/system_system_ila_0_1/bd_0/ip/ip_1/bd_1579_g_inst_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_1579_g_inst_0 || ORIG_REF_NAME==bd_1579_g_inst_0} -quiet] -quiet

# IP: e:/work/project_AXI_DMA/project_AXI_DMA.srcs/sources_1/bd/system/ip/system_system_ila_0_1/bd_0/ip/ip_2/bd_1579_slot_0_aw_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_1579_slot_0_aw_0 || ORIG_REF_NAME==bd_1579_slot_0_aw_0} -quiet] -quiet

# IP: e:/work/project_AXI_DMA/project_AXI_DMA.srcs/sources_1/bd/system/ip/system_system_ila_0_1/bd_0/ip/ip_3/bd_1579_slot_0_w_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_1579_slot_0_w_0 || ORIG_REF_NAME==bd_1579_slot_0_w_0} -quiet] -quiet

# IP: e:/work/project_AXI_DMA/project_AXI_DMA.srcs/sources_1/bd/system/ip/system_system_ila_0_1/bd_0/ip/ip_4/bd_1579_slot_0_b_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_1579_slot_0_b_0 || ORIG_REF_NAME==bd_1579_slot_0_b_0} -quiet] -quiet

# IP: e:/work/project_AXI_DMA/project_AXI_DMA.srcs/sources_1/bd/system/ip/system_system_ila_0_1/bd_0/ip/ip_5/bd_1579_slot_0_ar_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_1579_slot_0_ar_0 || ORIG_REF_NAME==bd_1579_slot_0_ar_0} -quiet] -quiet

# IP: e:/work/project_AXI_DMA/project_AXI_DMA.srcs/sources_1/bd/system/ip/system_system_ila_0_1/bd_0/ip/ip_6/bd_1579_slot_0_r_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_1579_slot_0_r_0 || ORIG_REF_NAME==bd_1579_slot_0_r_0} -quiet] -quiet

# XDC: e:/work/project_AXI_DMA/project_AXI_DMA.srcs/sources_1/bd/system/ip/system_system_ila_0_1/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_1579_ila_lib_0 || ORIG_REF_NAME==bd_1579_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: e:/work/project_AXI_DMA/project_AXI_DMA.srcs/sources_1/bd/system/ip/system_system_ila_0_1/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_1579_ila_lib_0 || ORIG_REF_NAME==bd_1579_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: e:/work/project_AXI_DMA/project_AXI_DMA.srcs/sources_1/bd/system/ip/system_system_ila_0_1/bd_0/ip/ip_0/bd_1579_ila_lib_0_ooc.xdc

# XDC: e:/work/project_AXI_DMA/project_AXI_DMA.srcs/sources_1/bd/system/ip/system_system_ila_0_1/bd_0/bd_1579_ooc.xdc
