set_property SRC_FILE_INFO {cfile:E:/work/project_AXI_DMA/project_AXI_DMA.srcs/constrs_1/new/IO_constrain.xdc rfile:../../../project_AXI_DMA.srcs/constrs_1/new/IO_constrain.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L14 [get_ports key]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H15 [get_ports m0_axi_txn_done_0]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L15 [get_ports m0_axi_error_0]
